BEGIN TRANSACTION;
DROP TABLE IF EXISTS `players`;
CREATE TABLE IF NOT EXISTS `players` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT UNIQUE,
	`category`	INTEGER,
	FOREIGN KEY(`category`) REFERENCES `player_category`(`id`) ON DELETE CASCADE
);
DROP TABLE IF EXISTS `player_information`;
CREATE TABLE IF NOT EXISTS `player_information` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`player_id`	INTEGER NOT NULL,
	`value`	INTEGER NOT NULL DEFAULT 0,
	`matches`	INTEGER NOT NULL DEFAULT 0,
	`runs`	INTEGER NOT NULL DEFAULT 0,
	`100`	INTEGER NOT NULL DEFAULT 0,
	`50`	INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY(`player_id`) REFERENCES `players`(`id`) ON DELETE CASCADE
);
DROP TABLE IF EXISTS `player_category`;
CREATE TABLE IF NOT EXISTS `player_category` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL UNIQUE
);
DROP TABLE IF EXISTS `matches`;
CREATE TABLE IF NOT EXISTS `matches` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`player_id`	INTEGER UNIQUE,
	`faced`	INTEGER NOT NULL DEFAULT 0,
	`fours`	INTEGER NOT NULL DEFAULT 0,
	`sixes`	INTEGER NOT NULL DEFAULT 0,
	`bowled`	INTEGER NOT NULL DEFAULT 0,
	`maiden`	INTEGER NOT NULL DEFAULT 0,
	`given`	INTEGER NOT NULL DEFAULT 0,
	`wkts`	INTEGER NOT NULL DEFAULT 0,
	`catches`	INTEGER NOT NULL DEFAULT 0,
	`stumping`	INTEGER NOT NULL DEFAULT 0,
	`un_out`	INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY(`player_id`) REFERENCES `players`(`id`) ON DELETE CASCADE
);
DROP INDEX IF EXISTS `player_matches_details`;
CREATE INDEX IF NOT EXISTS `player_matches_details` ON `matches` (
	`player_id`	ASC
);
COMMIT;
